import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Firefighters | Fight your way out of the fire',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
        <body
          className={cn(
            'relative h-full font-sans antialiased ',
            inter.className,
          )}
        >
          <main className=" flex flex-col min-h-screen">
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </body>
    </html>
  );
}
